### ISSUE TITLE
Integration ESTW Kempten

### ISSUE THREAD

**Issue by jannikbecker** [jannikbecker/leibit#37]

**Comment by dfoehl** [comment]
Hey,
ich schau mir gerade Kempten an. Der HBF hat ja die Gleise 1N/1S, welche laut dem Fahrplan immer nur als Gleis 1 angesprochen werden (Ob Süd oder Nord steht dann in den Hinweisen). Ist das nun richtig als "track 1" mit "track 1S" und "track 1N" oder als "track 1" mit den beiden blocks drin?

**Comment by jannikbecker** [comment]
Moin. Sehr gut, dass du dich um MKP kümmerst 👍

Ich würde das Gleis 1 (ohne direkte Block Zuordnung) erfassen und dann zwei Kind-Gleise 1N und 1S (jeweils mit Block Zuordnung). Analog dann natürlich für Gleis 2 und 5. Wichtig ist, dass die Alternativen für die Gleise 1, 2, 3, 4, 5 und 6 konfiguriert sind, damit bspw. nicht 1S Alternative für 3 ist, sondern das "gesamte" Gleis 1.

Schau dir mal Bremen Hbf als Referenz an, dort gibt es genau die gleiche Situation.

**Comment by dfoehl** [comment]
Ok, hab ich so gemacht. Ich hab mich ein wenig durch VS irritieren lassen, das mir "alternative" nicht mehr im Bereich nach den beiden Kind-Gleisen vorgeschlagen hatte...
PR kommt dann in den nächsten Tagen.

**Comment by jannikbecker** [comment]
Moin, wie ist hier aktuell der Stand @dfoehl ?
