### ISSUE TITLE
Vorzeitige Wenden werden falsch dargstellt

### ISSUE THREAD

**Issue by dfoehl** [jannikbecker/leibit#68]
Bei einer Vorzeitigen Wende wird bei der neuen Zugnummer der ursprüngliche Startbahnhof als durchfahren (+0) angezeigt. Diesen hat der Zug jedoch nie passiert.

**Comment by jannikbecker** [comment]
Kannst du das bitte mal mit der aktuellen Version (0.2.3) ausprobieren? Ich hatte letzte Woche die Darstellung im Zuglauf diesbezüglich angepasst.

**Comment by dfoehl** [comment]
Passt, die Änderungen hast du glaub auch erst gestern Abend eingecheckt, das hatte ich noch nicht in meinem Repository :)
![grafik](https://user-images.githubusercontent.com/7548596/91769589-f5112f80-ebdf-11ea-8ee1-90e5af802c1b.png)

**Comment by jannikbecker** [comment]
Ja, genau. Wobei in dem rechten Screenshot noch der rote Kreis beim Startbahnhof fehlt. Das ist aber nur ne Kleinigkeit, die ich mir beizeiten mal anschaue.
