### ISSUE TITLE
In TF Hafen wird der 32152 nicht in LeiBit verbucht

### ISSUE THREAD

**Issue by dfoehl** [jannikbecker/leibit#88]
Bei meinem Spiel wurde gerade der 32152 nicht im Leibit verbucht (+99) obwohl er schon länger dort stand. In der .dat stand die Nummer folgendermaßen drin: `08:23: 07G152//// 32152__ 0 82 L`
In der XML ist das Gleis als `7G152` definiert, sorgt das ggf. für Probleme? Beim 153 habe ich den Fehler bisher nicht bemerkt, dort ist die Konstellation theoretisch die gleiche.

**Comment by jannikbecker** [comment]
Moin. Du hast das Problem schon genau richtig erkannt. In dem XML muss der Eintrag genau so lauten wie in der .dat Datei, also "07G152" bzw. "07G153". Sonst funktionierts nicht.
